---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ragflow-service-config
data:
  {{- with .Values.ragflow.service_conf }}
  local.service_conf.yaml: |
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Values.ragflow.llm_factories }}
  llm_factories.json: |
    {{- . | toPrettyJson | nindent 4 }}
  {{- end }}
