// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'C:/Users/zfc/Desktop/doc/ragflow/web/src/pages/add-knowledge/components/knowledge-file/model';
import model_2 from 'C:/Users/zfc/Desktop/doc/ragflow/web/src/pages/add-knowledge/components/knowledge-setting/model';
import model_3 from 'C:/Users/zfc/Desktop/doc/ragflow/web/src/pages/add-knowledge/model';
import model_4 from 'C:/Users/zfc/Desktop/doc/ragflow/web/src/pages/chat/model';
import model_5 from 'C:/Users/zfc/Desktop/doc/ragflow/web/src/pages/knowledge/model';
import model_6 from 'C:/Users/zfc/Desktop/doc/ragflow/web/src/pages/login/model';
import model_7 from 'C:/Users/zfc/Desktop/doc/ragflow/web/src/pages/setting/model';

export const models = {
model_1: { namespace: 'add-knowledge.components.knowledge-file.model', model: model_1 },
model_2: { namespace: 'add-knowledge.components.knowledge-setting.model', model: model_2 },
model_3: { namespace: 'add-knowledge.model', model: model_3 },
model_4: { namespace: 'chat.model', model: model_4 },
model_5: { namespace: 'knowledge.model', model: model_5 },
model_6: { namespace: 'login.model', model: model_6 },
model_7: { namespace: 'setting.model', model: model_7 },
} as const
