version: "3.9"

services:
  ragflow-worker:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    container_name: ragflow-worker
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
    networks:
      - ragflow
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["python", "rag/svr/task_executor.py", "--worker"]

networks:
  ragflow:
    driver: bridge
