//go:build cgo && !integration

package native

// fillpoly_align_test.go verifies the pure-Go fillPoly rasterization bit-for-bit
// against cv2.fillPoly, using the golden generated by gen_fillpoly_golden.py
// (Python cv2 4.10.0). The score computed by boxScoreFast is mean(pred) over
// the masked pixels, so mask-alignment is necessary and sufficient for the
// det score to match deepdoc — this is the dominant source of gap-3 orphans.
//
// Run:
//   go test -run TestFillPolyAlignsCV2 ./native/...

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

type fillPolyCase struct {
	Mw   int          `json:"mw"`
	Mh   int          `json:"mh"`
	Quad [][2]float64 `json:"quad"`
	Mask []int        `json:"mask"`
}

func loadFillPolyGolden(t *testing.T) []fillPolyCase {
	raw, err := os.ReadFile(filepath.Join("testdata", "mp_cn_sm_p0.fillpoly.golden.json"))
	if err != nil {
		t.Fatalf("read fillpoly golden: %v", err)
	}
	var cases []fillPolyCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatalf("parse fillpoly golden: %v", err)
	}
	return cases
}

func TestFillPolyAlignsCV2(t *testing.T) {
	cases := loadFillPolyGolden(t)
	var totalPix, mismPix, mismatchCases int
	var examples []string
	for ci, c := range cases {
		if len(c.Quad) != 4 {
			t.Fatalf("case %d: quad has %d pts", ci, len(c.Quad))
		}
		var poly [4]pt
		for i := range c.Quad {
			poly[i] = pt{X: c.Quad[i][0], Y: c.Quad[i][1]}
		}
		gmask := make([]bool, c.Mw*c.Mh)
		fillPoly(gmask, c.Mw, c.Mh, poly)
		if len(gmask) != len(c.Mask) {
			t.Fatalf("case %d: mask size %d != %d", ci, len(gmask), len(c.Mask))
		}
		caseMismatch := 0
		for i := range gmask {
			cv := c.Mask[i] != 0
			totalPix++
			if gmask[i] != cv {
				mismPix++
				caseMismatch++
			}
		}
		if caseMismatch > 0 {
			mismatchCases++
			if len(examples) < 10 {
				examples = append(examples,
					fmt.Sprintf("case %d mw=%d mh=%d mismatched=%d quad=%v",
						ci, c.Mw, c.Mh, caseMismatch, c.Quad))
			}
		}
	}
	t.Logf("fillPoly vs cv2: %d cases, %d pixels, %d mismatched pixels, %d cases with mismatch",
		len(cases), totalPix, mismPix, mismatchCases)
	for _, e := range examples {
		t.Logf("  %s", e)
	}
	if mismPix > 0 {
		t.Errorf("fillPoly diverges from cv2.fillPoly: %d/%d pixels, %d/%d cases",
			mismPix, totalPix, mismatchCases, len(cases))
	}
}
