package util

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"image"
	"image/color"
	"image/png"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestWarpCropMatchesGolden locks the perspective de-skew behaviour of
// WarpCrop against a reference warp (PIL PERSPECTIVE, BICUBIC) generated by
// testdata/gen_warp_golden.py. The reference uses the same homogeneous
// mapping as cv2.getPerspectiveTransform + warpPerspective, so this test pins
// the geometry (output size + de-skew) of the Go implementation. Minor
// resampling-kernel differences between PIL-bicubic and the Go Catmull-Rom
// sampler are absorbed by the MSE tolerance.
//
// This is the unit-tier (model-free) lock for Step 4 / layer 1 of the Go↔Python
// OCR parity work: the warp step of deepdoc/vision/ocr.py get_rotate_crop_image.
func TestWarpCropMatchesGolden(t *testing.T) {
	metaPath := filepath.Join("testdata", "warp_meta.json")
	metaBytes, err := os.ReadFile(metaPath)
	if err != nil {
		t.Fatalf("read meta: %v", err)
	}
	var meta struct {
		Src [4][2]float64 `json:"src"`
		W   int           `json:"w"`
		H   int           `json:"h"`
	}
	if err := json.Unmarshal(metaBytes, &meta); err != nil {
		t.Fatalf("parse meta: %v", err)
	}
	var pts [4]Pt
	for i := range meta.Src {
		pts[i] = Pt{X: meta.Src[i][0], Y: meta.Src[i][1]}
	}

	src := loadGolden(t, filepath.Join("testdata", "warp_src.b64"))
	expected := loadGolden(t, filepath.Join("testdata", "warp_expected.b64"))

	got := WarpCrop(src, pts)

	// Output size must match Python exactly: W = int(max(|p0-p1|,|p2-p3|)),
	// H = int(max(|p0-p3|,|p1-p2|)).
	if got.Bounds().Dx() != meta.W || got.Bounds().Dy() != meta.H {
		t.Fatalf("output size = %dx%d, want %dx%d",
			got.Bounds().Dx(), got.Bounds().Dy(), meta.W, meta.H)
	}
	if expected.Bounds().Dx() != meta.W || expected.Bounds().Dy() != meta.H {
		t.Fatalf("golden size = %dx%d, want %dx%d",
			expected.Bounds().Dx(), expected.Bounds().Dy(), meta.W, meta.H)
	}

	mse := imageMSE(got, expected)
	t.Logf("WarpCrop vs golden MSE = %.4f (RMSE/channel = %.4f)", mse, math.Sqrt(mse))

	// Generous enough to absorb resampling-kernel differences, tight enough
	// to catch a grossly wrong implementation (e.g. an axis-aligned crop of
	// the same quad would diverge by orders of magnitude on this skewed input).
	const maxMSE = 30.0
	if mse > maxMSE {
		t.Errorf("WarpCrop de-skew diverges from golden: MSE=%.4f > %.4f", mse, maxMSE)
	}

	// Sanity: WarpCrop must actually de-skew, not just return an axis-aligned
	// bbox crop of the quad. On this perspective (non-parallelogram) input the
	// output dimensions differ from the axis-aligned bbox, so the two are
	// trivially unequal — confirm that rather than asserting a number.
	bbox := axisFallback(src, pts)
	if bbox.Bounds().Dx() == meta.W && bbox.Bounds().Dy() == meta.H {
		t.Errorf("WarpCrop output size %dx%d equals the axis-aligned fallback size; warp may not be de-skewing",
			meta.W, meta.H)
	}
}

// TestWarpCropDegenerateQuadIsSafe checks that a collinear (degenerate) quad
// does not panic and returns a non-nil crop (falls back to axis-aligned).
func TestWarpCropDegenerateQuadIsSafe(t *testing.T) {
	src := image.NewRGBA(image.Rect(0, 0, 50, 50))
	// All four corners on a single line -> singular homography.
	pts := [4]Pt{{10, 10}, {20, 10}, {30, 10}, {40, 10}}
	got := WarpCrop(src, pts)
	if got == nil {
		t.Fatal("WarpCrop returned nil for degenerate quad")
	}
	if got.Bounds().Dx() <= 0 || got.Bounds().Dy() <= 0 {
		t.Errorf("WarpCrop returned empty crop for degenerate quad: %dx%d",
			got.Bounds().Dx(), got.Bounds().Dy())
	}
}

// TestWarpCropAxisAlignedQuadIsStable checks that an already axis-aligned,
// axis-parallel quad is reproduced (up to bicubic resampling) without
// distortion — i.e. the output matches the source sub-rect.
func TestWarpCropAxisAlignedQuadIsStable(t *testing.T) {
	src := image.NewRGBA(image.Rect(0, 0, 100, 100))
	// Fill with a checkerboard so resampling has signal.
	for y := 0; y < 100; y++ {
		for x := 0; x < 100; x++ {
			if ((x/10)+(y/10))%2 == 0 {
				src.SetRGBA(x, y, color.RGBA{0, 0, 0, 255})
			} else {
				src.SetRGBA(x, y, color.RGBA{255, 255, 255, 255})
			}
		}
	}
	// Exact axis-aligned rectangle -> output should match the source sub-rect.
	pts := [4]Pt{{20, 20}, {80, 20}, {80, 70}, {20, 70}}
	got := WarpCrop(src, pts)
	if got.Bounds().Dx() != 60 || got.Bounds().Dy() != 50 {
		t.Fatalf("axis-aligned output size = %dx%d, want 60x50",
			got.Bounds().Dx(), got.Bounds().Dy())
	}
	// For an axis-parallel quad the warp is identity (just a sub-rect copy),
	// so it must match FastCrop of the same bbox up to resampling error.
	want := FastCrop(src, 20, 20, 80, 70)
	mse := imageMSE(got, want)
	t.Logf("axis-aligned WarpCrop vs FastCrop MSE = %.4f", mse)
	if mse > 5.0 {
		t.Errorf("axis-aligned warp diverged from the source sub-rect: MSE=%.4f > 5.0", mse)
	}
}

// loadGolden reads a single-line base64-encoded PNG fixture (committed as
// text so pre-commit text filters cannot corrupt the binary signature).
func loadGolden(t *testing.T, path string) *image.RGBA {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	dec, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(raw)))
	if err != nil {
		t.Fatalf("base64 decode %s: %v", path, err)
	}
	img, err := png.Decode(bytes.NewReader(dec))
	if err != nil {
		t.Fatalf("decode %s: %v", path, err)
	}
	return toRGBA(img)
}

// imageMSE returns the mean squared error across all RGBA channels between a
// and b (both must have identical dimensions).
func imageMSE(a, b *image.RGBA) float64 {
	ba, bb := a.Bounds(), b.Bounds()
	if ba.Dx() != bb.Dx() || ba.Dy() != bb.Dy() {
		return math.MaxFloat64
	}
	var acc float64
	n := ba.Dx() * ba.Dy()
	for y := 0; y < ba.Dy(); y++ {
		for x := 0; x < ba.Dx(); x++ {
			ca := a.RGBAAt(x, y)
			cb := b.RGBAAt(x, y)
			acc += sqDiff(ca.R, cb.R) + sqDiff(ca.G, cb.G) + sqDiff(ca.B, cb.B) + sqDiff(ca.A, cb.A)
		}
	}
	return acc / float64(n*4)
}

func sqDiff(x, y uint8) float64 {
	d := float64(x) - float64(y)
	return d * d
}
