TIMEOUT_SECONDS = 60
TIMEOUT_ATTEMPTS = 2
FAIL_AFTER_EMBEDDING = 10
FAIL_AFTER_CHAT = 30

def set_high_timeout():
    global TIMEOUT_SECONDS, TIMEOUT_ATTEMPTS, FAIL_AFTER_EMBEDDING, FAIL_AFTER_CHAT
    TIMEOUT_SECONDS = 750
    TIMEOUT_ATTEMPTS = 5
    FAIL_AFTER_EMBEDDING = 60
    FAIL_AFTER_CHAT = 150

def reset_timeout():
    global TIMEOUT_SECONDS, TIMEOUT_ATTEMPTS, FAIL_AFTER_EMBEDDING, FAIL_AFTER_CHAT
    TIMEOUT_SECONDS = 60
    TIMEOUT_ATTEMPTS = 2
    FAIL_AFTER_EMBEDDING = 10
    FAIL_AFTER_CHAT = 30
