// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/proto/ingestion.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestionServer_Action_FullMethodName = "/common.IngestionServer/Action"
)

// IngestionServerClient is the client API for IngestionServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestionServerClient interface {
	Action(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestionMessage, IngestionResponse], error)
}

type ingestionServerClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionServerClient(cc grpc.ClientConnInterface) IngestionServerClient {
	return &ingestionServerClient{cc}
}

func (c *ingestionServerClient) Action(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestionMessage, IngestionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestionServer_ServiceDesc.Streams[0], IngestionServer_Action_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestionMessage, IngestionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionServer_ActionClient = grpc.BidiStreamingClient[IngestionMessage, IngestionResponse]

// IngestionServerServer is the server API for IngestionServer service.
// All implementations must embed UnimplementedIngestionServerServer
// for forward compatibility.
type IngestionServerServer interface {
	Action(grpc.BidiStreamingServer[IngestionMessage, IngestionResponse]) error
	mustEmbedUnimplementedIngestionServerServer()
}

// UnimplementedIngestionServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionServerServer struct{}

func (UnimplementedIngestionServerServer) Action(grpc.BidiStreamingServer[IngestionMessage, IngestionResponse]) error {
	return status.Error(codes.Unimplemented, "method Action not implemented")
}
func (UnimplementedIngestionServerServer) mustEmbedUnimplementedIngestionServerServer() {}
func (UnimplementedIngestionServerServer) testEmbeddedByValue()                         {}

// UnsafeIngestionServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionServerServer will
// result in compilation errors.
type UnsafeIngestionServerServer interface {
	mustEmbedUnimplementedIngestionServerServer()
}

func RegisterIngestionServerServer(s grpc.ServiceRegistrar, srv IngestionServerServer) {
	// If the following call panics, it indicates UnimplementedIngestionServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionServer_ServiceDesc, srv)
}

func _IngestionServer_Action_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestionServerServer).Action(&grpc.GenericServerStream[IngestionMessage, IngestionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionServer_ActionServer = grpc.BidiStreamingServer[IngestionMessage, IngestionResponse]

// IngestionServer_ServiceDesc is the grpc.ServiceDesc for IngestionServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestionServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.IngestionServer",
	HandlerType: (*IngestionServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Action",
			Handler:       _IngestionServer_Action_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/ingestion.proto",
}
