// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/proto/ingestion.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestionManager_Action_FullMethodName = "/common.IngestionManager/Action"
)

// IngestionManagerClient is the client API for IngestionManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestionManagerClient interface {
	Action(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestionMessage, AdminMessage], error)
}

type ingestionManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionManagerClient(cc grpc.ClientConnInterface) IngestionManagerClient {
	return &ingestionManagerClient{cc}
}

func (c *ingestionManagerClient) Action(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestionMessage, AdminMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestionManager_ServiceDesc.Streams[0], IngestionManager_Action_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestionMessage, AdminMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionManager_ActionClient = grpc.BidiStreamingClient[IngestionMessage, AdminMessage]

// IngestionManagerServer is the server API for IngestionManager service.
// All implementations must embed UnimplementedIngestionManagerServer
// for forward compatibility.
type IngestionManagerServer interface {
	Action(grpc.BidiStreamingServer[IngestionMessage, AdminMessage]) error
	mustEmbedUnimplementedIngestionManagerServer()
}

// UnimplementedIngestionManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionManagerServer struct{}

func (UnimplementedIngestionManagerServer) Action(grpc.BidiStreamingServer[IngestionMessage, AdminMessage]) error {
	return status.Error(codes.Unimplemented, "method Action not implemented")
}
func (UnimplementedIngestionManagerServer) mustEmbedUnimplementedIngestionManagerServer() {}
func (UnimplementedIngestionManagerServer) testEmbeddedByValue()                          {}

// UnsafeIngestionManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionManagerServer will
// result in compilation errors.
type UnsafeIngestionManagerServer interface {
	mustEmbedUnimplementedIngestionManagerServer()
}

func RegisterIngestionManagerServer(s grpc.ServiceRegistrar, srv IngestionManagerServer) {
	// If the following call panics, it indicates UnimplementedIngestionManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionManager_ServiceDesc, srv)
}

func _IngestionManager_Action_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestionManagerServer).Action(&grpc.GenericServerStream[IngestionMessage, AdminMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionManager_ActionServer = grpc.BidiStreamingServer[IngestionMessage, AdminMessage]

// IngestionManager_ServiceDesc is the grpc.ServiceDesc for IngestionManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestionManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.IngestionManager",
	HandlerType: (*IngestionManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Action",
			Handler:       _IngestionManager_Action_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/ingestion.proto",
}
