// Please lowercase the file name
export const IconMap = {
  'Tongyi-Qianwen': 'tongyi',
  Moonshot: 'moonshot',
  OpenAI: 'openai',
  'ZHIPU-AI': 'zhipu',
  文心一言: 'wenxin',
  Ollama: 'ollama',
  Xinference: 'xinference',
  DeepSeek: 'deepseek',
  VolcEngine: 'volc_engine',
  BaiChuan: 'baichuan',
  Jina: 'jina',
  MiniMax: 'chat-minimax',
  Mistral: 'mistral',
  'Azure-OpenAI': 'azure',
  Bedrock: 'bedrock',
  Gemini: 'gemini',
  Groq: 'groq-next',
  OpenRouter: 'open-router',
  LocalAI: 'local-ai',
  StepFun: 'stepfun',
  NVIDIA: 'nvidia',
  'LM-Studio': 'lm-studio',
  'OpenAI-API-Compatible': 'openai-api',
  cohere: 'cohere',
  LeptonAI: 'lepton-ai',
  TogetherAI: 'together-ai',
  PerfXCloud: 'perfx-cloud',
  Upstage: 'upstage',
  'novita.ai': 'novita-ai',
  SILICONFLOW: 'siliconflow',
  '01.AI': 'yi',
  Replicate: 'replicate',
  'Tencent Hunyuan': 'hunyuan',
  'XunFei Spark': 'spark',
  BaiduYiyan: 'yiyan',
  'Fish Audio': 'fish-audio',
  'Tencent Cloud': 'tencent-cloud',
  Anthropic: 'anthropic',
  'Voyage AI': 'voyage',
  'Google Cloud': 'google-cloud',
  HuggingFace: 'huggingface',
};

export const BedrockRegionList = [
  'us-east-1',
  'us-west-2',
  'ap-southeast-1',
  'ap-northeast-1',
  'eu-central-1',
  'us-gov-west-1',
  'ap-southeast-2',
];
